port: 8888
test: false
nacos:
  ip_addr: 3.7.191.1
  context_path: /nacos
  port: 8848
api:
  path: /test
  response_content_type: 1
  protocol: 1
  request_method: 1
  request_params:
    - name: id
      type: 1
      required: true
      condition: id IN (?)
      value: "001,002,003"
    - name: name
      type: 1
      required: false
      condition: name LIKE ?
      value: "张"
data_source:
  service:
    name: datasource-operation-nl
  info:
    id: 1430132288963739648
    ip: 3.7.191.8
    port: 25308
    db_name: test4g
    username: test4g
    password: Thinker@123
    schema: public
    dsource_type: 1
    sql: select * from table_name
    count_sql: select count(*) from table_name
